name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: balthazar-backend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install AWS CLI and ECS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          sudo chmod +x /usr/local/bin/ecs-cli

      - name: Create ECS Cluster if it doesn't exist
        env:
          AWS_REGION: ap-southeast-2
          CLUSTER_NAME: balthazar-backend
        run: |
          CLUSTER_STATUS=$(aws ecs describe-clusters --clusters ${CLUSTER_NAME} --query 'clusters[0].status' --output text || echo "MISSING")
          if [ "$CLUSTER_STATUS" == "MISSING" ]; then
            echo "Creating ECS cluster..."
            aws ecs create-cluster --cluster-name ${CLUSTER_NAME}
          elif [ "$CLUSTER_STATUS" == "INACTIVE" ]; then
            echo "Cluster is inactive, recreating..."
            aws ecs create-cluster --cluster-name ${CLUSTER_NAME}
          else
            echo "ECS cluster already exists!"
          fi

      - name: Create CloudWatch Log Group if it doesn't exist
        env:
          AWS_REGION: ap-southeast-2
          LOG_GROUP_NAME: /ecs/balthazar-backend-service
        run: |
          LOG_GROUP_STATUS=$(aws logs describe-log-groups --log-group-name-prefix ${LOG_GROUP_NAME} --query 'logGroups[0].logGroupName' --output text || echo "MISSING")
          if [ "$LOG_GROUP_STATUS" == "MISSING" ] || [ "$LOG_GROUP_STATUS" == "None" ]; then
            echo "Creating CloudWatch log group..."
            aws logs create-log-group --log-group-name ${LOG_GROUP_NAME}
          else
            echo "CloudWatch log group already exists."
          fi

      - name: Create Target Group if it doesn't exist
        env:
          AWS_REGION: ap-southeast-2
          VPC_ID: vpc-090404bcbc53bc3d0 # Replace with your actual VPC ID
          TARGET_GROUP_NAME: balthazar-tg
        run: |
          TARGET_GROUP_ARN=$(aws elbv2 describe-target-groups --names ${TARGET_GROUP_NAME} --query 'TargetGroups[0].TargetGroupArn' --output text || echo "MISSING")
          if [ "$TARGET_GROUP_ARN" == "MISSING" ]; then
            echo "Creating Target Group..."
            TARGET_GROUP_ARN=$(aws elbv2 create-target-group --name ${TARGET_GROUP_NAME} --protocol HTTP --port 3001 --vpc-id ${VPC_ID} --target-type ip --query 'TargetGroups[0].TargetGroupArn' --output text)
          else
            echo "Target Group already exists."
          fi
          echo "TARGET_GROUP_ARN=$TARGET_GROUP_ARN" >> $GITHUB_ENV

      - name: Create Load Balancer if it doesn't exist
        env:
          AWS_REGION: ap-southeast-2
          VPC_ID: vpc-090404bcbc53bc3d0 # Replace with your actual VPC ID
          LOAD_BALANCER_NAME: balthazar-alb
        run: |
          LOAD_BALANCER_ARN=$(aws elbv2 describe-load-balancers --names ${LOAD_BALANCER_NAME} --query 'LoadBalancers[0].LoadBalancerArn' --output text || echo "MISSING")
          if [ "$LOAD_BALANCER_ARN" == "MISSING" ]; then
            echo "Creating Load Balancer..."
            LOAD_BALANCER_ARN=$(aws elbv2 create-load-balancer --name ${LOAD_BALANCER_NAME} --subnets ${SUBNET_ID} --security-groups ${SECURITY_GROUP_ID} --scheme internet-facing --type application --query 'LoadBalancers[0].LoadBalancerArn' --output text)
          else
            echo "Load Balancer already exists."
          fi
          echo "LOAD_BALANCER_ARN=$LOAD_BALANCER_ARN" >> $GITHUB_ENV

      - name: Attach Target Group to Load Balancer
        env:
          AWS_REGION: ap-southeast-2
          LOAD_BALANCER_ARN: ${{ env.LOAD_BALANCER_ARN }}
          TARGET_GROUP_ARN: ${{ env.TARGET_GROUP_ARN }}
        run: |
          LISTENER_ARN=$(aws elbv2 describe-listeners --load-balancer-arn ${LOAD_BALANCER_ARN} --query 'Listeners[0].ListenerArn' --output text || echo "MISSING")
          if [ "$LISTENER_ARN" == "MISSING" ]; then
            echo "Creating Listener for Load Balancer..."
            LISTENER_ARN=$(aws elbv2 create-listener --load-balancer-arn ${LOAD_BALANCER_ARN} --protocol HTTP --port 80 --default-actions Type=forward,TargetGroupArn=${TARGET_GROUP_ARN} --query 'Listeners[0].ListenerArn' --output text)
          else
            echo "Listener already exists."
          fi
          echo "LISTENER_ARN=$LISTENER_ARN" >> $GITHUB_ENV

      - name: Create ECS Service if it doesn't exist
        env:
          AWS_REGION: ap-southeast-2
          CLUSTER_NAME: balthazar-backend
          SERVICE_NAME: balthazar-backend-service
          TASK_DEFINITION: balthazar-task
          SUBNET_ID: subnet-0ab2124445e116c31 # Replace with your actual Subnet ID
          SECURITY_GROUP_ID: sg-0e1be39336e6b9288 # Replace with your actual Security Group ID
        run: |
          SERVICE_STATUS=$(aws ecs describe-services --cluster ${CLUSTER_NAME} --services ${SERVICE_NAME} --query 'failures[0].reason' --output text)
          if [ "$SERVICE_STATUS" == "MISSING" ] || [ "$SERVICE_STATUS" == "None" ]; then
            echo "Creating ECS service..."
            aws ecs create-service --cluster ${CLUSTER_NAME} --service-name ${SERVICE_NAME} --task-definition ${TASK_DEFINITION} --desired-count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[${SUBNET_ID}],securityGroups=[${SECURITY_GROUP_ID}],assignPublicIp='ENABLED'}" --load-balancers "targetGroupArn=${{ env.TARGET_GROUP_ARN }},containerName=balthazar-backend,containerPort=3001"
          else
            echo "ECS service already exists."
          fi

      - name: Register Task Definition and Update ECS Service
        env:
          AWS_REGION: ap-southeast-2
          CLUSTER_NAME: balthazar-backend
          SERVICE_NAME: balthazar-backend-service
          TASK_DEFINITION: balthazar-task
          CONTAINER_NAME: balthazar-backend
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: balthazar-backend
          IMAGE_TAG: latest
        run: |
          # Create the task definition JSON file
          cat <<EOF > taskdef.json
          {
            "family": "${TASK_DEFINITION}",
            "networkMode": "awsvpc",
            "executionRoleArn": "arn:aws:iam::727210836757:role/ecsTaskExecutionRole",  # Replace with your actual execution role ARN
            "taskRoleArn": "arn:aws:iam::727210836757:role/taskRoleArn",  # Replace with your actual task role ARN
            "containerDefinitions": [
              {
                "name": "${CONTAINER_NAME}",
                "image": "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}",
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 3001,
                    "hostPort": 3001
                  }
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/${SERVICE_NAME}",
                    "awslogs-region": "${AWS_REGION}",
                    "awslogs-stream-prefix": "ecs"
                  }
                }
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512"
          }
          EOF

          # Register the task definition
          aws ecs register-task-definition --cli-input-json file://taskdef.json

          # Update the ECS service to use the new task definition
          aws ecs update-service --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME} --force-new-deployment
